(let ((default-directory  "~/.emacs.d/elpa/"))
      (normal-top-level-add-subdirs-to-load-path))
(require 'dired-hide-dotfiles)

(menu-bar-mode -1)
(setq-default mode-line-format nil)
(put 'dired-find-alternate-file 'disabled nil)
(defun mode-of (b)
    (buffer-local-value 'major-mode b))
(defun not-dired-p ()
    (not (eq (mode-of (current-buffer)) 'dired-mode)))
(defun dired-alive-p ()
    (seq-some (lambda (b) (eq (mode-of b) 'dired-mode)) (buffer-list)))
(defun kill-emacs-on-dired-exit ()
    (interactive) 
        (if (and (dired-alive-p) (not-dired-p))
            (kill-buffer)
            (kill-emacs)))
(global-set-key (kbd "q") 'kill-emacs-on-dired-exit)
(eval-after-load "dired"
                 '(progn 
                   (define-key dired-mode-map (kbd "q") 'kill-emacs-on-dired-exit)
                   (define-key dired-mode-map "." #'dired-hide-dotfiles-mode)
                   (add-hook 'dired-mode-hook 'dired-hide-dotfiles-mode)))
(add-hook 'find-file-hook 'read-only-mode)
(dired default-directory)
