(let ((default-directory  "~/.emacs.d/elpa/"))
      (normal-top-level-add-subdirs-to-load-path))
(require 'magit)

(menu-bar-mode -1)
(setq-default mode-line-format nil)
(defun mode-of (b)
    (buffer-local-value 'major-mode b))
(defun magit-alive-p ()
    (seq-some (lambda (b) (eq (mode-of b) 'magit-status-mode)) (buffer-list)))
(defun kill-emacs-on-magit-exit ()
    (interactive) 
        (if (and (magit-alive-p) (not (eq (mode-of (current-buffer)) 'magit-status-mode)))
            (kill-buffer)
            (kill-emacs)))
(define-key magit-status-mode-map (kbd "q") 'kill-emacs-on-magit-exit)
(global-set-key (kbd "q") 'kill-emacs-on-magit-exit)
(magit)
(delete-other-windows)
