(let ((default-directory  "~/.emacs.d/elpa/"))
      (normal-top-level-add-subdirs-to-load-path))
(require 'telega)

(menu-bar-mode -1)
(setq-default mode-line-format nil)
(defun mode-of (b)
    (buffer-local-value 'major-mode b))
(defun telega-alive-p ()
    (seq-some (lambda (b) (eq (mode-of b) 'telega-root-mode)) (buffer-list)))
(defun kill-emacs-on-telega-exit ()
    (interactive) 
        (if (and (telega-alive-p) (not (eq (mode-of (current-buffer)) 'telega-root-mode)))
            (kill-buffer)
            (kill-emacs)))
(define-key telega-root-mode-map (kbd "q") 'kill-emacs-on-telega-exit)
(define-key telega-chat-mode-map (kbd "q") 'kill-emacs-on-telega-exit)
(global-set-key (kbd "q") 'kill-emacs-on-telega-exit)
(setq telega-symbol-underline-bar "=")
(setq telega-symbol-heavy-checkmark "☑")
(setq telega-accounts '(("ego" telega-database-dir "/home/ego/.telega/ego")
                        ("pub" telega-database-dir "/home/ego/.telega/pub")))
(telega)
